// <auto-generated />
using Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(TransporteContext))]
    [Migration("20230624220442_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Caracteristica", b =>
                {
                    b.Property<int>("CaracteristicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaracteristicaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("CaracteristicaId");

                    b.ToTable("Caracteristica");

                    b.HasData(
                        new
                        {
                            CaracteristicaId = 1,
                            Descripcion = "Cantidad de Asientos"
                        },
                        new
                        {
                            CaracteristicaId = 2,
                            Descripcion = "Tipo de Asientos"
                        },
                        new
                        {
                            CaracteristicaId = 3,
                            Descripcion = "Velocidad Maxima"
                        });
                });

            modelBuilder.Entity("Domain.CaracteristicaTransporte", b =>
                {
                    b.Property<int>("CaracteristicaTransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaracteristicaTransporteId"));

                    b.Property<int>("CaracteristicaId")
                        .HasColumnType("int");

                    b.Property<int>("TransporteId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("CaracteristicaTransporteId");

                    b.HasIndex("CaracteristicaId");

                    b.HasIndex("TransporteId");

                    b.ToTable("CaracteristicaTransporte");

                    b.HasData(
                        new
                        {
                            CaracteristicaTransporteId = 1,
                            CaracteristicaId = 1,
                            TransporteId = 1,
                            Valor = "50"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 2,
                            CaracteristicaId = 1,
                            TransporteId = 2,
                            Valor = "60"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 3,
                            CaracteristicaId = 2,
                            TransporteId = 2,
                            Valor = "SemiCama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 4,
                            CaracteristicaId = 1,
                            TransporteId = 3,
                            Valor = "360"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 5,
                            CaracteristicaId = 3,
                            TransporteId = 3,
                            Valor = "300 km/h"
                        });
                });

            modelBuilder.Entity("Domain.CompaniaTransporte", b =>
                {
                    b.Property<int>("CompaniaTransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniaTransporteId"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("CompaniaTransporteId");

                    b.ToTable("CompaniaTransporte");

                    b.HasData(
                        new
                        {
                            CompaniaTransporteId = 1,
                            Cuit = "0147852369",
                            RazonSocial = "PLUSMAR"
                        },
                        new
                        {
                            CompaniaTransporteId = 2,
                            Cuit = "15615612232",
                            RazonSocial = "Chevalier"
                        },
                        new
                        {
                            CompaniaTransporteId = 3,
                            Cuit = "21561665662",
                            RazonSocial = "Sarmiento SRL"
                        },
                        new
                        {
                            CompaniaTransporteId = 4,
                            Cuit = "123456789",
                            RazonSocial = "Roca"
                        },
                        new
                        {
                            CompaniaTransporteId = 5,
                            Cuit = "1561232",
                            RazonSocial = "Despegar"
                        },
                        new
                        {
                            CompaniaTransporteId = 6,
                            Cuit = "156789456",
                            RazonSocial = "Aerolineas Argentinas"
                        });
                });

            modelBuilder.Entity("Domain.TipoTransporte", b =>
                {
                    b.Property<int>("TipoTransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoTransporteId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("TipoTransporteId");

                    b.ToTable("TipoTransporte");

                    b.HasData(
                        new
                        {
                            TipoTransporteId = 1,
                            Descripcion = "Avion"
                        },
                        new
                        {
                            TipoTransporteId = 2,
                            Descripcion = "Micro"
                        },
                        new
                        {
                            TipoTransporteId = 3,
                            Descripcion = "Tren"
                        });
                });

            modelBuilder.Entity("Domain.Transporte", b =>
                {
                    b.Property<int>("TransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransporteId"));

                    b.Property<int>("CompaniaTransporteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTransporteId")
                        .HasColumnType("int");

                    b.HasKey("TransporteId");

                    b.HasIndex("CompaniaTransporteId");

                    b.HasIndex("TipoTransporteId");

                    b.ToTable("Transporte");

                    b.HasData(
                        new
                        {
                            TransporteId = 1,
                            CompaniaTransporteId = 5,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 2,
                            CompaniaTransporteId = 1,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 3,
                            CompaniaTransporteId = 3,
                            TipoTransporteId = 3
                        });
                });

            modelBuilder.Entity("Domain.CaracteristicaTransporte", b =>
                {
                    b.HasOne("Domain.Caracteristica", "Caracteristica")
                        .WithMany("CaracteristicaTransporte")
                        .HasForeignKey("CaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Transporte", "Transporte")
                        .WithMany("CaracteristicaTransporte")
                        .HasForeignKey("TransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristica");

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("Domain.Transporte", b =>
                {
                    b.HasOne("Domain.CompaniaTransporte", "CompaniaTransporte")
                        .WithMany("Transporte")
                        .HasForeignKey("CompaniaTransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.TipoTransporte", "TipoTransporte")
                        .WithMany("Transporte")
                        .HasForeignKey("TipoTransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompaniaTransporte");

                    b.Navigation("TipoTransporte");
                });

            modelBuilder.Entity("Domain.Caracteristica", b =>
                {
                    b.Navigation("CaracteristicaTransporte");
                });

            modelBuilder.Entity("Domain.CompaniaTransporte", b =>
                {
                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("Domain.TipoTransporte", b =>
                {
                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("Domain.Transporte", b =>
                {
                    b.Navigation("CaracteristicaTransporte");
                });
#pragma warning restore 612, 618
        }
    }
}
