// <auto-generated />
using Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(TransporteContext))]
    [Migration("20230703200704_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Caracteristica", b =>
                {
                    b.Property<int>("CaracteristicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaracteristicaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("CaracteristicaId");

                    b.ToTable("Caracteristica");

                    b.HasData(
                        new
                        {
                            CaracteristicaId = 1,
                            Descripcion = "Cantidad de Asientos"
                        },
                        new
                        {
                            CaracteristicaId = 2,
                            Descripcion = "Tipo de Asientos"
                        },
                        new
                        {
                            CaracteristicaId = 3,
                            Descripcion = "Velocidad Maxima"
                        });
                });

            modelBuilder.Entity("Domain.CaracteristicaTransporte", b =>
                {
                    b.Property<int>("CaracteristicaTransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaracteristicaTransporteId"));

                    b.Property<int>("CaracteristicaId")
                        .HasColumnType("int");

                    b.Property<int>("TransporteId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("CaracteristicaTransporteId");

                    b.HasIndex("CaracteristicaId");

                    b.HasIndex("TransporteId");

                    b.ToTable("CaracteristicaTransporte");

                    b.HasData(
                        new
                        {
                            CaracteristicaTransporteId = 1,
                            CaracteristicaId = 1,
                            TransporteId = 1,
                            Valor = "300"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 2,
                            CaracteristicaId = 1,
                            TransporteId = 2,
                            Valor = "85"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 3,
                            CaracteristicaId = 2,
                            TransporteId = 2,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 4,
                            CaracteristicaId = 1,
                            TransporteId = 3,
                            Valor = "250"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 5,
                            CaracteristicaId = 3,
                            TransporteId = 3,
                            Valor = "300 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 6,
                            CaracteristicaId = 1,
                            TransporteId = 4,
                            Valor = "300"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 7,
                            CaracteristicaId = 2,
                            TransporteId = 4,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 8,
                            CaracteristicaId = 3,
                            TransporteId = 4,
                            Valor = "660 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 9,
                            CaracteristicaId = 1,
                            TransporteId = 5,
                            Valor = "350"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 10,
                            CaracteristicaId = 2,
                            TransporteId = 5,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 11,
                            CaracteristicaId = 3,
                            TransporteId = 5,
                            Valor = "500 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 12,
                            CaracteristicaId = 1,
                            TransporteId = 6,
                            Valor = "275"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 13,
                            CaracteristicaId = 2,
                            TransporteId = 6,
                            Valor = "Asiento Ejecutivo"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 14,
                            CaracteristicaId = 3,
                            TransporteId = 6,
                            Valor = "900 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 15,
                            CaracteristicaId = 1,
                            TransporteId = 7,
                            Valor = "300"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 16,
                            CaracteristicaId = 2,
                            TransporteId = 7,
                            Valor = "Asiento Econ贸mico"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 17,
                            CaracteristicaId = 3,
                            TransporteId = 7,
                            Valor = "800 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 18,
                            CaracteristicaId = 1,
                            TransporteId = 8,
                            Valor = "290"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 19,
                            CaracteristicaId = 2,
                            TransporteId = 8,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 20,
                            CaracteristicaId = 3,
                            TransporteId = 8,
                            Valor = "800 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 21,
                            CaracteristicaId = 1,
                            TransporteId = 9,
                            Valor = "350"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 22,
                            CaracteristicaId = 2,
                            TransporteId = 9,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 23,
                            CaracteristicaId = 3,
                            TransporteId = 9,
                            Valor = "500 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 24,
                            CaracteristicaId = 1,
                            TransporteId = 10,
                            Valor = "330"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 25,
                            CaracteristicaId = 2,
                            TransporteId = 10,
                            Valor = "Asiento Ejecutivo"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 26,
                            CaracteristicaId = 3,
                            TransporteId = 10,
                            Valor = "1000 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 27,
                            CaracteristicaId = 1,
                            TransporteId = 11,
                            Valor = "280"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 28,
                            CaracteristicaId = 2,
                            TransporteId = 11,
                            Valor = "Asiento Ejecutivo"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 29,
                            CaracteristicaId = 3,
                            TransporteId = 11,
                            Valor = "950 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 30,
                            CaracteristicaId = 1,
                            TransporteId = 12,
                            Valor = "250"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 31,
                            CaracteristicaId = 2,
                            TransporteId = 12,
                            Valor = "Asiento Econ贸mico"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 32,
                            CaracteristicaId = 3,
                            TransporteId = 12,
                            Valor = "700 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 33,
                            CaracteristicaId = 1,
                            TransporteId = 13,
                            Valor = "350"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 34,
                            CaracteristicaId = 2,
                            TransporteId = 13,
                            Valor = "Asiento Econ贸mico"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 35,
                            CaracteristicaId = 3,
                            TransporteId = 13,
                            Valor = "600 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 36,
                            CaracteristicaId = 1,
                            TransporteId = 14,
                            Valor = "280"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 37,
                            CaracteristicaId = 2,
                            TransporteId = 14,
                            Valor = "Asiento Econ贸mico"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 38,
                            CaracteristicaId = 3,
                            TransporteId = 14,
                            Valor = "500 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 39,
                            CaracteristicaId = 1,
                            TransporteId = 15,
                            Valor = "300"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 40,
                            CaracteristicaId = 2,
                            TransporteId = 15,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 41,
                            CaracteristicaId = 3,
                            TransporteId = 15,
                            Valor = "850 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 42,
                            CaracteristicaId = 1,
                            TransporteId = 16,
                            Valor = "315"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 43,
                            CaracteristicaId = 2,
                            TransporteId = 16,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 44,
                            CaracteristicaId = 3,
                            TransporteId = 16,
                            Valor = "800 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 45,
                            CaracteristicaId = 1,
                            TransporteId = 17,
                            Valor = "265"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 46,
                            CaracteristicaId = 2,
                            TransporteId = 17,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 47,
                            CaracteristicaId = 3,
                            TransporteId = 17,
                            Valor = "800 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 48,
                            CaracteristicaId = 1,
                            TransporteId = 18,
                            Valor = "310"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 49,
                            CaracteristicaId = 2,
                            TransporteId = 18,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 50,
                            CaracteristicaId = 3,
                            TransporteId = 18,
                            Valor = "750 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 51,
                            CaracteristicaId = 1,
                            TransporteId = 19,
                            Valor = "85"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 52,
                            CaracteristicaId = 2,
                            TransporteId = 19,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 53,
                            CaracteristicaId = 3,
                            TransporteId = 19,
                            Valor = "120 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 54,
                            CaracteristicaId = 1,
                            TransporteId = 20,
                            Valor = "80"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 55,
                            CaracteristicaId = 2,
                            TransporteId = 20,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 56,
                            CaracteristicaId = 3,
                            TransporteId = 20,
                            Valor = "120 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 57,
                            CaracteristicaId = 1,
                            TransporteId = 21,
                            Valor = "75"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 58,
                            CaracteristicaId = 2,
                            TransporteId = 21,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 59,
                            CaracteristicaId = 3,
                            TransporteId = 21,
                            Valor = "120 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 60,
                            CaracteristicaId = 1,
                            TransporteId = 22,
                            Valor = "85"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 61,
                            CaracteristicaId = 2,
                            TransporteId = 22,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 62,
                            CaracteristicaId = 3,
                            TransporteId = 22,
                            Valor = "150 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 63,
                            CaracteristicaId = 1,
                            TransporteId = 23,
                            Valor = "80"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 64,
                            CaracteristicaId = 2,
                            TransporteId = 23,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 65,
                            CaracteristicaId = 3,
                            TransporteId = 23,
                            Valor = "120 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 66,
                            CaracteristicaId = 1,
                            TransporteId = 24,
                            Valor = "75"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 67,
                            CaracteristicaId = 2,
                            TransporteId = 24,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 68,
                            CaracteristicaId = 3,
                            TransporteId = 24,
                            Valor = "120 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 69,
                            CaracteristicaId = 1,
                            TransporteId = 25,
                            Valor = "85"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 70,
                            CaracteristicaId = 2,
                            TransporteId = 25,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 71,
                            CaracteristicaId = 3,
                            TransporteId = 25,
                            Valor = "100 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 72,
                            CaracteristicaId = 1,
                            TransporteId = 26,
                            Valor = "80"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 73,
                            CaracteristicaId = 2,
                            TransporteId = 26,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 74,
                            CaracteristicaId = 3,
                            TransporteId = 26,
                            Valor = "110 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 75,
                            CaracteristicaId = 1,
                            TransporteId = 27,
                            Valor = "75"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 76,
                            CaracteristicaId = 2,
                            TransporteId = 27,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 77,
                            CaracteristicaId = 3,
                            TransporteId = 27,
                            Valor = "130 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 78,
                            CaracteristicaId = 1,
                            TransporteId = 28,
                            Valor = "85"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 79,
                            CaracteristicaId = 2,
                            TransporteId = 28,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 80,
                            CaracteristicaId = 3,
                            TransporteId = 28,
                            Valor = "130 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 81,
                            CaracteristicaId = 1,
                            TransporteId = 29,
                            Valor = "80"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 82,
                            CaracteristicaId = 2,
                            TransporteId = 29,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 83,
                            CaracteristicaId = 3,
                            TransporteId = 29,
                            Valor = "100 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 84,
                            CaracteristicaId = 1,
                            TransporteId = 30,
                            Valor = "75"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 85,
                            CaracteristicaId = 2,
                            TransporteId = 30,
                            Valor = "Cama Ejecutivo"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 86,
                            CaracteristicaId = 3,
                            TransporteId = 30,
                            Valor = "150 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 87,
                            CaracteristicaId = 1,
                            TransporteId = 31,
                            Valor = "85"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 88,
                            CaracteristicaId = 2,
                            TransporteId = 31,
                            Valor = "Cama Ejecutivo"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 89,
                            CaracteristicaId = 3,
                            TransporteId = 31,
                            Valor = "160 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 90,
                            CaracteristicaId = 1,
                            TransporteId = 32,
                            Valor = "80"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 91,
                            CaracteristicaId = 2,
                            TransporteId = 32,
                            Valor = "Cama Ejecutivo"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 92,
                            CaracteristicaId = 3,
                            TransporteId = 32,
                            Valor = "190 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 93,
                            CaracteristicaId = 1,
                            TransporteId = 33,
                            Valor = "75"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 94,
                            CaracteristicaId = 2,
                            TransporteId = 33,
                            Valor = "Cama Ejecutivo"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 95,
                            CaracteristicaId = 3,
                            TransporteId = 33,
                            Valor = "200 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 96,
                            CaracteristicaId = 1,
                            TransporteId = 34,
                            Valor = "200"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 97,
                            CaracteristicaId = 2,
                            TransporteId = 34,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 98,
                            CaracteristicaId = 3,
                            TransporteId = 34,
                            Valor = "150 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 99,
                            CaracteristicaId = 1,
                            TransporteId = 35,
                            Valor = "220"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 100,
                            CaracteristicaId = 2,
                            TransporteId = 35,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 101,
                            CaracteristicaId = 3,
                            TransporteId = 35,
                            Valor = "150 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 102,
                            CaracteristicaId = 1,
                            TransporteId = 36,
                            Valor = "240"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 103,
                            CaracteristicaId = 2,
                            TransporteId = 36,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 104,
                            CaracteristicaId = 3,
                            TransporteId = 36,
                            Valor = "150 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 105,
                            CaracteristicaId = 1,
                            TransporteId = 37,
                            Valor = "200"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 106,
                            CaracteristicaId = 2,
                            TransporteId = 37,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 107,
                            CaracteristicaId = 3,
                            TransporteId = 37,
                            Valor = "180 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 108,
                            CaracteristicaId = 1,
                            TransporteId = 38,
                            Valor = "220"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 109,
                            CaracteristicaId = 2,
                            TransporteId = 38,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 110,
                            CaracteristicaId = 3,
                            TransporteId = 38,
                            Valor = "160 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 111,
                            CaracteristicaId = 1,
                            TransporteId = 39,
                            Valor = "240"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 112,
                            CaracteristicaId = 2,
                            TransporteId = 39,
                            Valor = "Semi Cama"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 113,
                            CaracteristicaId = 3,
                            TransporteId = 39,
                            Valor = "150 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 114,
                            CaracteristicaId = 1,
                            TransporteId = 40,
                            Valor = "200"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 115,
                            CaracteristicaId = 2,
                            TransporteId = 40,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 116,
                            CaracteristicaId = 3,
                            TransporteId = 40,
                            Valor = "180 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 117,
                            CaracteristicaId = 1,
                            TransporteId = 41,
                            Valor = "220"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 118,
                            CaracteristicaId = 2,
                            TransporteId = 41,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 119,
                            CaracteristicaId = 3,
                            TransporteId = 41,
                            Valor = "180 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 120,
                            CaracteristicaId = 1,
                            TransporteId = 42,
                            Valor = "240"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 121,
                            CaracteristicaId = 2,
                            TransporteId = 42,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 122,
                            CaracteristicaId = 3,
                            TransporteId = 42,
                            Valor = "170 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 123,
                            CaracteristicaId = 1,
                            TransporteId = 43,
                            Valor = "200"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 124,
                            CaracteristicaId = 2,
                            TransporteId = 43,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 125,
                            CaracteristicaId = 3,
                            TransporteId = 43,
                            Valor = "180 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 126,
                            CaracteristicaId = 1,
                            TransporteId = 44,
                            Valor = "220"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 127,
                            CaracteristicaId = 2,
                            TransporteId = 44,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 128,
                            CaracteristicaId = 3,
                            TransporteId = 44,
                            Valor = "190 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 129,
                            CaracteristicaId = 1,
                            TransporteId = 45,
                            Valor = "240"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 130,
                            CaracteristicaId = 2,
                            TransporteId = 45,
                            Valor = "Asiento Regular"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 131,
                            CaracteristicaId = 3,
                            TransporteId = 45,
                            Valor = "180 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 132,
                            CaracteristicaId = 1,
                            TransporteId = 46,
                            Valor = "200"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 133,
                            CaracteristicaId = 2,
                            TransporteId = 46,
                            Valor = "Cama Ejecutivo"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 134,
                            CaracteristicaId = 3,
                            TransporteId = 46,
                            Valor = "200 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 135,
                            CaracteristicaId = 1,
                            TransporteId = 47,
                            Valor = "220"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 136,
                            CaracteristicaId = 2,
                            TransporteId = 47,
                            Valor = "Cama Ejecutivo"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 137,
                            CaracteristicaId = 3,
                            TransporteId = 47,
                            Valor = "250 Km/h"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 138,
                            CaracteristicaId = 1,
                            TransporteId = 48,
                            Valor = "240"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 139,
                            CaracteristicaId = 2,
                            TransporteId = 48,
                            Valor = "Cama Ejecutivo"
                        },
                        new
                        {
                            CaracteristicaTransporteId = 140,
                            CaracteristicaId = 3,
                            TransporteId = 48,
                            Valor = "250 Km/h"
                        });
                });

            modelBuilder.Entity("Domain.CompaniaTransporte", b =>
                {
                    b.Property<int>("CompaniaTransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniaTransporteId"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ImagenLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("CompaniaTransporteId");

                    b.ToTable("CompaniaTransporte");

                    b.HasData(
                        new
                        {
                            CompaniaTransporteId = 1,
                            Cuit = "0147852369",
                            ImagenLogo = "https://upload.wikimedia.org/wikipedia/commons/5/5e/Plusmar_logo.png",
                            RazonSocial = "PLUSMAR"
                        },
                        new
                        {
                            CompaniaTransporteId = 2,
                            Cuit = "15615612232",
                            ImagenLogo = "https://www.centraldepasajes.com.ar/empresas-de-micro/img/logos/chevallier-logo.png",
                            RazonSocial = "Chevalier"
                        },
                        new
                        {
                            CompaniaTransporteId = 3,
                            Cuit = "21561665662",
                            ImagenLogo = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Ferrocarriles_Argentinos.svg/1280px-Ferrocarriles_Argentinos.svg.png",
                            RazonSocial = "Sarmiento SRL"
                        },
                        new
                        {
                            CompaniaTransporteId = 4,
                            Cuit = "123456789",
                            ImagenLogo = "https://yt3.googleusercontent.com/r2dUpnRqDqQ8g-P17-UTpv5LZ7SuJGBNxto_Wp-OCwnJ9q0saSxGs1GQyov8LNftLYNJExTiqw=s900-c-k-c0x00ffffff-no-rj",
                            RazonSocial = "Roca"
                        },
                        new
                        {
                            CompaniaTransporteId = 5,
                            Cuit = "1561232",
                            ImagenLogo = "https://flybondi.com/static/media/logo.ebbd0b77.svg",
                            RazonSocial = "Flybondi"
                        },
                        new
                        {
                            CompaniaTransporteId = 6,
                            Cuit = "156789456",
                            ImagenLogo = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Aerol%C3%ADneas_Argentinas_Logo_2010.svg/512px-Aerol%C3%ADneas_Argentinas_Logo_2010.svg.png",
                            RazonSocial = "Aerolineas Argentinas"
                        },
                        new
                        {
                            CompaniaTransporteId = 7,
                            Cuit = "1561482123",
                            ImagenLogo = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Qatar_Airways_Logo.png/800px-Qatar_Airways_Logo.png",
                            RazonSocial = "Qatar Airways"
                        });
                });

            modelBuilder.Entity("Domain.TipoTransporte", b =>
                {
                    b.Property<int>("TipoTransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoTransporteId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("TipoTransporteId");

                    b.ToTable("TipoTransporte");

                    b.HasData(
                        new
                        {
                            TipoTransporteId = 1,
                            Descripcion = "Avion"
                        },
                        new
                        {
                            TipoTransporteId = 2,
                            Descripcion = "Micro"
                        },
                        new
                        {
                            TipoTransporteId = 3,
                            Descripcion = "Tren"
                        });
                });

            modelBuilder.Entity("Domain.Transporte", b =>
                {
                    b.Property<int>("TransporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransporteId"));

                    b.Property<int>("CompaniaTransporteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTransporteId")
                        .HasColumnType("int");

                    b.HasKey("TransporteId");

                    b.HasIndex("CompaniaTransporteId");

                    b.HasIndex("TipoTransporteId");

                    b.ToTable("Transporte");

                    b.HasData(
                        new
                        {
                            TransporteId = 1,
                            CompaniaTransporteId = 5,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 2,
                            CompaniaTransporteId = 1,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 3,
                            CompaniaTransporteId = 3,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 4,
                            CompaniaTransporteId = 5,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 5,
                            CompaniaTransporteId = 6,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 6,
                            CompaniaTransporteId = 7,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 7,
                            CompaniaTransporteId = 5,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 8,
                            CompaniaTransporteId = 6,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 9,
                            CompaniaTransporteId = 7,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 10,
                            CompaniaTransporteId = 5,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 11,
                            CompaniaTransporteId = 6,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 12,
                            CompaniaTransporteId = 7,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 13,
                            CompaniaTransporteId = 5,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 14,
                            CompaniaTransporteId = 6,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 15,
                            CompaniaTransporteId = 7,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 16,
                            CompaniaTransporteId = 5,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 17,
                            CompaniaTransporteId = 6,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 18,
                            CompaniaTransporteId = 7,
                            TipoTransporteId = 1
                        },
                        new
                        {
                            TransporteId = 19,
                            CompaniaTransporteId = 1,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 20,
                            CompaniaTransporteId = 1,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 21,
                            CompaniaTransporteId = 1,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 22,
                            CompaniaTransporteId = 1,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 23,
                            CompaniaTransporteId = 1,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 24,
                            CompaniaTransporteId = 1,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 25,
                            CompaniaTransporteId = 1,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 26,
                            CompaniaTransporteId = 2,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 27,
                            CompaniaTransporteId = 2,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 28,
                            CompaniaTransporteId = 2,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 29,
                            CompaniaTransporteId = 2,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 30,
                            CompaniaTransporteId = 2,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 31,
                            CompaniaTransporteId = 2,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 32,
                            CompaniaTransporteId = 2,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 33,
                            CompaniaTransporteId = 2,
                            TipoTransporteId = 2
                        },
                        new
                        {
                            TransporteId = 34,
                            CompaniaTransporteId = 3,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 35,
                            CompaniaTransporteId = 3,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 36,
                            CompaniaTransporteId = 3,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 37,
                            CompaniaTransporteId = 3,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 38,
                            CompaniaTransporteId = 3,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 39,
                            CompaniaTransporteId = 3,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 40,
                            CompaniaTransporteId = 3,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 41,
                            CompaniaTransporteId = 4,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 42,
                            CompaniaTransporteId = 4,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 43,
                            CompaniaTransporteId = 4,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 44,
                            CompaniaTransporteId = 4,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 45,
                            CompaniaTransporteId = 4,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 46,
                            CompaniaTransporteId = 4,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 47,
                            CompaniaTransporteId = 4,
                            TipoTransporteId = 3
                        },
                        new
                        {
                            TransporteId = 48,
                            CompaniaTransporteId = 4,
                            TipoTransporteId = 3
                        });
                });

            modelBuilder.Entity("Domain.CaracteristicaTransporte", b =>
                {
                    b.HasOne("Domain.Caracteristica", "Caracteristica")
                        .WithMany("CaracteristicaTransporte")
                        .HasForeignKey("CaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Transporte", "Transporte")
                        .WithMany("CaracteristicaTransporte")
                        .HasForeignKey("TransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristica");

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("Domain.Transporte", b =>
                {
                    b.HasOne("Domain.CompaniaTransporte", "CompaniaTransporte")
                        .WithMany("Transporte")
                        .HasForeignKey("CompaniaTransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.TipoTransporte", "TipoTransporte")
                        .WithMany("Transporte")
                        .HasForeignKey("TipoTransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompaniaTransporte");

                    b.Navigation("TipoTransporte");
                });

            modelBuilder.Entity("Domain.Caracteristica", b =>
                {
                    b.Navigation("CaracteristicaTransporte");
                });

            modelBuilder.Entity("Domain.CompaniaTransporte", b =>
                {
                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("Domain.TipoTransporte", b =>
                {
                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("Domain.Transporte", b =>
                {
                    b.Navigation("CaracteristicaTransporte");
                });
#pragma warning restore 612, 618
        }
    }
}
